server:
  port: 8084

user:
  age: 18
  books-name: 三国演义
  book:
    bookName: 计算机基础
    bookPrice: 102




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyg
    username: root
    password: 123456